### ISSUE TITLE
Crash when running any command

### ISSUE THREAD

**Issue by ericmj** [heroku/heroku-repo#47]
```
 !    Heroku client internal error.
 !    Search for help at: https://help.heroku.com
 !    Or report a bug at: https://github.com/heroku/heroku/issues/new

    Error:       undefined method `index' for #<Heroku::Command::Run:0x007fa56f044388> (NoMethodError)
    Command:     heroku repo:purge_cache
    Plugins:     heroku-anvil
                 heroku-repo
                 heroku-vim

    Version:     heroku-toolbelt/3.42.22 (x86_64-darwin14.0.0) ruby/1.9.3
    Error ID:    bbe4e35baead4d0caee0f4f217e811a9


    More information in /Users/ericmj/.heroku/error.log
```

error.log:
```
Heroku client internal error.
undefined method `index' for #<Heroku::Command::Run:0x007fa56f044388>
/Users/ericmj/.heroku/plugins/heroku-repo/lib/heroku/command/repo.rb:147:in `run'
/Users/ericmj/.heroku/plugins/heroku-repo/lib/heroku/command/repo.rb:37:in `purge_cache'
/usr/local/Cellar/heroku-toolbelt/3.42.22/libexec/lib/heroku/command.rb:212:in `run'
/usr/local/Cellar/heroku-toolbelt/3.42.22/libexec/lib/heroku/cli.rb:30:in `start'
/usr/local/Cellar/heroku-toolbelt/3.42.22/libexec/bin/heroku:24:in `<main>'
```

**Comment by dickeyxxx** [comment]
can you update your plugins? `heroku plugins:update`

**Comment by ericmj** [comment]
Updating worked, thanks.
