### ISSUE TITLE
Errors when installing plugin

### ISSUE THREAD

**Issue by jongbeau** [heroku/heroku-repo#53]
After yesterday's commit, i'm getting errors when installing the plugin:

```
ubuntu@box43:~$ heroku plugins:install heroku-repo
Installing plugin heroku-repo.../home/ubuntu/.heroku/node_modules/heroku-repo/node_modules/heroku-cli-util/lib/action.js:16
  if (options.then) [options, promise] = [{}, options]
                    ^^^^^^^^^^^^^^^^^^

ReferenceError: Invalid left-hand side in assignment
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/home/ubuntu/.heroku/node_modules/heroku-repo/node_modules/heroku-cli-util/index.js:11:18)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
```

I'm running node v5.0.0 and npm v3.10.2

**Comment by dickeyxxx** [comment]
what is the output of `heroku version`?

**Comment by jongbeau** [comment]
```
ubuntu@box198:~$ heroku version
heroku-toolbelt/3.43.0 (x86_64-linux) ruby/1.9.3
heroku-cli/4.30.0-2dfc0f4 (amd64-linux) go1.6.2
=== Installed Plugins
heroku-apps@2.0.2
heroku-cli-addons@0.3.0
heroku-fork@4.1.2
heroku-git@2.5.1
heroku-local@5.0.2
heroku-orgs@1.0.8
heroku-pipelines@1.1.4
heroku-run@3.2.0
heroku-spaces@2.1.2
heroku-status@2.1.4
```

**Comment by dickeyxxx** [comment]
Your CLI is out of date. What happens if you run `heroku update`?

**Comment by jongbeau** [comment]
That fixed it. Thanks! Now just need to get CircleCI to update their heroku version.
